# Generated by Django 6.1.1 on 2026-09-20 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(db_index=True, max_length=20)),
                ('risk_percent', models.FloatField(help_text='Evaluated failure probability percentage')),
                ('status', models.CharField(help_text='Operational status (WARNING, HIGH FAILURE RISK, etc.)', max_length=50)),
                ('recipients', models.TextField(help_text='Comma-separated email recipients')),
                ('email_status', models.CharField(help_text='Status: sent, failed, cooldown_skipped, disabled', max_length=30)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'alert_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='idx_alert_time')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(db_index=True, help_text='Machine identifier (e.g. M01, M02, M03)', max_length=20)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('vibration', models.FloatField(help_text='Vibration speed in mm/s')),
                ('current', models.FloatField(help_text='Operating current in Amperes')),
                ('rpm', models.IntegerField(help_text='Rotational speed in RPM')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sensor_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['machine_id', '-recorded_at'], name='idx_machine_time')],
            },
        ),
    ]
